package agent

import "github.com/luma-cli/lumer-cli/shortcuts/common"

// Shortcuts returns backend-owned prompt abilities.
func Shortcuts() []common.Shortcut {
	return []common.Shortcut{
		{
			ID:          "subtitle.split",
			Service:     "agent",
			Command:     "run subtitle.split",
			Description: "Split text into subtitle segments through backend-owned prompt logic.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "input", Description: "Payload JSON path.", Required: true},
				{Name: "output", Description: "Output JSON path."},
			},
			Outputs:  []string{"segments", "sentence_groups", "output_path"},
			Examples: []string{"luma-cli agent run subtitle.split --input payload.json --output split.json"},
			Skills:   []string{"luma-subtitle"},
		},
		{
			ID:          "subtitle.highlight",
			Service:     "agent",
			Command:     "run subtitle.highlight",
			Description: "Assign subtitle highlight keywords through backend-owned prompt logic.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"highlights", "output_path"},
			Examples:    []string{"luma-cli agent run subtitle.highlight --input segments.json --output highlights.json"},
			Skills:      []string{"luma-subtitle"},
		},
		{
			ID:          "subtitle.effects",
			Service:     "agent",
			Command:     "run subtitle.effects",
			Description: "Assign subtitle effects through backend-owned prompt logic.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"effects", "output_path"},
			Examples:    []string{"luma-cli agent run subtitle.effects --input segments.json --output effects.json"},
			Skills:      []string{"luma-subtitle"},
		},
		{
			ID:          "script.write",
			Service:     "agent",
			Command:     "run script.write",
			Description: "Write a structured spoken video script from profile, selected topic, evidence coverage, and material deliverables.",
			Risk:        "network",
			Flags:       []common.Flag{{Name: "input", Description: "Script writer payload JSON path.", Required: true}, {Name: "output", Description: "Output script JSON path."}},
			Outputs:     []string{"title", "hook", "sections", "full_script", "evidence_notes", "risk_notes", "estimated_duration_sec", "usage", "output_path"},
			Examples:    []string{"luma-cli agent run script.write --input 06_script_writer_payload_topic_002.json --output 07_script_topic_002.json"},
			Skills:      []string{"luma-content-script"},
		},
		{
			ID:          "title.generate",
			Service:     "agent",
			Command:     "run title.generate",
			Description: "Generate video title, cover copy, and tags through backend-owned prompt logic.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"cover_title", "cover_subtitle", "video_title", "tags", "output_path"},
			Examples:    []string{"luma-cli agent run title.generate --input title_payload.json --output title.json"},
		},
		{
			ID:          "storyboard.scene",
			Service:     "agent",
			Command:     "run storyboard.scene",
			Description: "Generate picture-in-picture scene plan through backend-owned prompt logic.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"scene_units", "output_path"},
			Examples:    []string{"luma-cli agent run storyboard.scene --input segments.json --output scene.json"},
		},
		{
			ID:          "storyboard.shot",
			Service:     "agent",
			Command:     "run storyboard.shot",
			Description: "Generate multi-shot table from scene units.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"shot_units", "output_path"},
			Examples:    []string{"luma-cli agent run storyboard.shot --input scene_payload.json --output shots.json"},
			Skills:      []string{"luma-digital-human"},
		},
		{
			ID:          "material.match",
			Service:     "agent",
			Command:     "run material.match",
			Description: "Match picture-in-picture materials to scene units through backend-owned prompt logic.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"inserts", "output_path"},
			Examples:    []string{"luma-cli agent run material.match --input match_payload.json --output inserts.json"},
		},
		{
			ID:          "agent.pip.plan",
			Service:     "agent",
			Command:     "run pip.plan",
			Description: "Build a worker-facing picture-in-picture insert payload from scenes and matched materials.",
			Risk:        "write",
			Flags:       []common.Flag{{Name: "input", Description: "Payload JSON path.", Required: true}, {Name: "output", Description: "Output JSON path."}},
			Outputs:     []string{"pip_plan", "worker_payload", "output_path"},
			Examples:    []string{"luma-cli agent run pip.plan --input pip_payload.json --output pip_plan.json"},
		},
	}
}
