package material

import "github.com/luma-cli/lumer-cli/shortcuts/common"

// Shortcuts returns local material metadata capabilities.
func Shortcuts() []common.Shortcut {
	return []common.Shortcut{
		{
			ID:          "material.describe",
			Service:     "material",
			Command:     "describe",
			Description: "Describe local image/video materials into an agent-readable JSON candidate list.",
			Risk:        "read",
			Flags: []common.Flag{
				{Name: "file_or_dir", Description: "Local material file or directory.", Required: true},
				{Name: "output", Description: "Output JSON path.", Default: "materials.json"},
			},
			Outputs:  []string{"materials", "output_path"},
			Examples: []string{"luma-cli material describe ./materials --output materials.json"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "material.group.list",
			Service:     "material",
			Command:     "group list",
			Description: "List ZA-AGENT style local material groups under a groups root directory.",
			Risk:        "read",
			Flags: []common.Flag{
				{Name: "groups_root", Description: "Directory containing material group folders.", Required: true},
				{Name: "output", Description: "Optional output JSON path."},
			},
			Outputs:  []string{"groups", "output_path"},
			Examples: []string{"luma-cli material group list ./material_library/groups --output material_groups.json"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "material.group.describe",
			Service:     "material",
			Command:     "group describe",
			Description: "Describe one local material group into a standard materials.json file, merging local meta files when present.",
			Risk:        "read",
			Flags: []common.Flag{
				{Name: "group_dir", Description: "One local material group directory.", Required: true},
				{Name: "output", Description: "Output JSON path.", Default: "materials.json"},
			},
			Outputs:  []string{"group", "materials", "output_path"},
			Examples: []string{"luma-cli material group describe ./material_library/groups/vlm_ai --output step4_materials_enriched.json"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "material.understand",
			Service:     "material",
			Command:     "understand",
			Description: "Upload one local material and get cloud semantic metadata for matching and PIP planning.",
			Risk:        "network",
			Flags: []common.Flag{
				{Name: "file", Description: "Local image/video material file.", Required: true},
				{Name: "group", Description: "Cloud resource group.", Default: "pip_materials"},
				{Name: "output", Description: "Semantic metadata JSON path.", Default: "material_meta.json"},
				{Name: "descriptor-output", Description: "Optional enriched single-material descriptor JSON path."},
			},
			Outputs:  []string{"group", "object_name", "output_path", "descriptor_output_path"},
			Examples: []string{"luma-cli material understand ./materials/a.mp4 --output a.meta.json --descriptor-output a.material.json"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "material.search",
			Service:     "material",
			Command:     "search",
			Description: "Search a local materials.json candidate list with deterministic keyword matching.",
			Risk:        "read",
			Flags: []common.Flag{
				{Name: "materials", Description: "Local material descriptors JSON path.", Required: true},
				{Name: "query", Description: "Search text from script, scene, or product claim.", Required: true},
				{Name: "limit", Description: "Maximum matches.", Default: "10"},
				{Name: "output", Description: "Optional output JSON path."},
			},
			Outputs:  []string{"query", "matches", "output_path"},
			Examples: []string{"luma-cli material search --materials step4_materials_enriched.json --query \"AI assistant\" --limit 5"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "material.merge",
			Service:     "material",
			Command:     "merge",
			Description: "Merge cloud material metadata back into a local materials.json descriptor file.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "materials", Description: "Local material descriptors JSON path.", Required: true},
				{Name: "meta", Description: "Material metadata JSON path or metadata directory.", Required: true},
				{Name: "output", Description: "Output enriched materials JSON path.", Default: "materials_enriched.json"},
			},
			Outputs:  []string{"materials", "output_path"},
			Examples: []string{"luma-cli material merge --materials materials.json --meta ./meta --output materials_enriched.json"},
			Skills:   []string{"luma-assets", "luma-video-workflow"},
		},
		{
			ID:          "pip.scan",
			Service:     "pip",
			Command:     "scan",
			Description: "Alias for local material description before PIP planning.",
			Risk:        "read",
			Flags: []common.Flag{
				{Name: "material_dir", Description: "Local material directory.", Required: true},
				{Name: "output", Description: "Output JSON path.", Default: "materials.json"},
			},
			Outputs:  []string{"materials", "output_path"},
			Examples: []string{"luma-cli pip scan ./materials --output materials.json"},
			Skills:   []string{"luma-video-workflow"},
		},
		{
			ID:          "pip.scene",
			Service:     "pip",
			Command:     "scene",
			Description: "Generate scene units from subtitle segments before material matching.",
			Risk:        "network",
			Flags: []common.Flag{
				{Name: "segments", Description: "Subtitle segments JSON path.", Required: true},
				{Name: "output", Description: "Output scene units JSON path.", Default: "step4_scene_units.json"},
			},
			Outputs:  []string{"output_path", "scene_count"},
			Examples: []string{"luma-cli pip scene --segments step4_segments.json --output step4_scene_units.json"},
			Skills:   []string{"luma-video-workflow", "luma-viral-remix-workflow"},
		},
		{
			ID:          "pip.match",
			Service:     "pip",
			Command:     "match",
			Description: "Match scene units with local material candidates, using cloud semantics or local keyword fallback.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "scenes", Description: "Scene units JSON path.", Required: true},
				{Name: "materials", Description: "Material candidates JSON path.", Required: true},
				{Name: "mode", Description: "Matching mode: auto, cloud, or local.", Default: "auto"},
				{Name: "max-inserts", Description: "Maximum PIP inserts.", Default: "8"},
				{Name: "output", Description: "Output match JSON path.", Default: "step4_material_matches.json"},
			},
			Outputs:  []string{"output_path", "matched_count", "mode"},
			Examples: []string{"luma-cli pip match --scenes step4_scene_units.json --materials step4_materials_enriched.json --mode auto --output step4_material_matches.json"},
			Skills:   []string{"luma-video-workflow", "luma-viral-remix-workflow"},
		},
		{
			ID:          "pip.plan",
			Service:     "pip",
			Command:     "plan",
			Description: "Generate a PIP plan from subtitle segments and local material candidates.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "segments", Description: "Subtitle segments JSON path.", Required: true},
				{Name: "materials", Description: "Material candidates JSON path.", Required: true},
				{Name: "output", Description: "Output plan JSON path.", Default: "step5_picture_in_picture_plan.json"},
				{Name: "match-mode", Description: "Matching mode: auto, cloud, or local.", Default: "auto"},
				{Name: "max-inserts", Description: "Maximum PIP inserts.", Default: "8"},
			},
			Outputs:  []string{"scene_units", "inserts", "output_path"},
			Examples: []string{"luma-cli pip plan --segments segments.json --materials materials.json --output step5_picture_in_picture_plan.json"},
			Skills:   []string{"luma-video-workflow"},
		},
		{
			ID:          "pip.render",
			Service:     "pip",
			Command:     "render",
			Description: "Render a PIP video locally from a standard PIP plan using ffmpeg.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "video", Description: "Source video path.", Required: true},
				{Name: "plan", Description: "PIP plan JSON path.", Required: true},
				{Name: "output", Description: "Output video path.", Default: "step5_picture_in_picture.mp4"},
				{Name: "landscape-height-ratio", Description: "Optional layout ratio override.", Default: "0.32"},
			},
			Outputs:  []string{"output_path", "plan_path"},
			Examples: []string{"luma-cli pip render source.mp4 --plan step5_picture_in_picture_plan.json --output step5_picture_in_picture.mp4"},
			Skills:   []string{"luma-video-workflow"},
		},
	}
}
