package media

import "github.com/luma-cli/lumer-cli/shortcuts/common"

// Shortcuts returns media generation and processing atomic capabilities.
func Shortcuts() []common.Shortcut {
	return []common.Shortcut{
		{
			ID:          "align.run",
			Service:     "align",
			Description: "Align subtitle segments to audio timestamps through cloud alignment API.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "audio", Description: "Local audio file (e.g. TTS output WAV).", Required: true},
				{Name: "segments", Description: "Segments JSON file with sentence_groups or segments.", Required: true},
				{Name: "output", Description: "Output aligned JSON path.", Default: "align_result.json"},
				{Name: "language", Description: "Recognition language.", Default: "zh"},
			},
			Outputs:  []string{"aligned_segments", "count", "output_path"},
			Examples: []string{"luma-cli align --audio tts.wav --segments step4_segments.json --output step4_aligned.json"},
			Skills:   []string{"luma-subtitle", "luma-video-workflow"},
		},
		{
			ID:          "asr.transcribe",
			Service:     "asr",
			Description: "Transcribe a local video or audio file through cloud ASR.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "file", Description: "Local video or audio file path.", Required: true},
				{Name: "language", Description: "Recognition language.", Default: "zh"},
				{Name: "output", Description: "Output ASR JSON path."},
			},
			Outputs:  []string{"task_id", "object_key", "text", "segments", "output_path"},
			Examples: []string{"luma-cli asr input.mp4 --language zh --output references/ref_01_asr.json"},
			Skills:   []string{"luma-subtitle", "luma-video-workflow", "luma-workflow-viral-remix"},
		},
		{
			ID:          "voice.clone",
			Service:     "voice",
			Command:     "clone",
			Description: "Upload reference audio as a reusable cloned voice for later TTS.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "sample_audio", Description: "Reference voice audio file.", Required: true},
				{Name: "name", Description: "Voice name used later by tts --voice."},
				{Name: "verbose", Description: "Show object key in output."},
			},
			Outputs:  []string{"name", "object_key"},
			Examples: []string{"luma-cli voice clone ./voice.wav --name my_voice"},
			Skills:   []string{"luma-digital-human", "luma-video-workflow", "luma-workflow-viral-remix"},
		},
		{
			ID:          "voice.list",
			Service:     "voice",
			Command:     "list",
			Description: "List reusable cloned voices.",
			Risk:        "read",
			Flags:       []common.Flag{{Name: "verbose", Description: "Show object keys."}},
			Outputs:     []string{"items"},
			Examples:    []string{"luma-cli voice list"},
			Skills:      []string{"luma-digital-human", "luma-video-workflow"},
		},
		{
			ID:          "tts.synthesize",
			Service:     "tts",
			Description: "Synthesize speech from text using a named voice asset.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "text", Description: "Text to synthesize.", Required: true},
				{Name: "voice", Description: "Voice friendly name or object key.", Default: "男声3"},
				{Name: "speech-rate", Description: "Speech rate multiplier.", Default: "1.1"},
				{Name: "trim-long-silence", Description: "Ask the backend to trim long pauses.", Default: "false"},
				{Name: "output", Description: "Output wav path.", Default: "step2_tts.wav"},
			},
			Outputs:  []string{"task_id", "audio_object_key", "output_path", "output_url"},
			Examples: []string{"luma-cli tts \"你好，欢迎来到直播间\" --voice 男声3"},
			Skills:   []string{"luma-digital-human", "luma-video-workflow"},
		},
		{
			ID:          "lipsync.create",
			Service:     "lipsync",
			Description: "Create a lip-sync digital human video from an avatar and audio.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "avatar", Description: "Avatar friendly name or object key.", Required: true},
				{Name: "audio", Description: "Local audio file path."},
				{Name: "audio-key", Description: "Cloud audio object key from TTS output. Skips upload when provided."},
				{Name: "output", Description: "Output video path.", Default: "step3_lipsync.mp4"},
				{Name: "random-start", Description: "Start the avatar video from a random position.", Default: "false"},
				{Name: "guidance-scale", Description: "Lip-sync guidance scale.", Default: "1.0"},
				{Name: "num-inference-steps", Description: "Inference steps.", Default: "15"},
				{Name: "no-superres", Description: "Disable super-resolution.", Default: "false"},
				{Name: "superres-scale", Description: "Super-resolution scale.", Default: "2"},
				{Name: "multi-shot-json", Description: "Path to backend multi_shot JSON payload."},
			},
			Outputs:  []string{"task_id", "output_path", "output_url"},
			Examples: []string{"luma-cli lipsync --avatar 数字人男 --audio tts_output.wav", "luma-cli lipsync --avatar 数字人男 --audio-key prod/resource/xxx/yyy.wav"},
			Skills:   []string{"luma-digital-human", "luma-video-workflow"},
		},
		{
			ID:          "video.enhance",
			Service:     "enhance",
			Description: "Enhance or upscale a local video.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "video", Description: "Local video file path.", Required: true},
				{Name: "scale", Description: "Upscale factor.", Default: "2"},
				{Name: "output", Description: "Output video path."},
			},
			Outputs:  []string{"task_id", "object_key", "output_path", "output_url"},
			Examples: []string{"luma-cli enhance input.mp4 --scale 2"},
			Skills:   []string{"luma-video-workflow"},
		},
		{
			ID:          "image.generate",
			Service:     "image",
			Command:     "generate",
			Description: "Generate one or more images from a prompt through the cloud media API.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "prompt", Description: "Image generation prompt.", Required: true},
				{Name: "count", Description: "Number of images.", Default: "1"},
				{Name: "aspect-ratio", Description: "Output aspect ratio.", Default: "9:16"},
				{Name: "resolution", Description: "Output resolution.", Default: "1K"},
				{Name: "output-dir", Description: "Directory for downloaded images.", Default: "generated_images"},
			},
			Outputs:  []string{"task_id", "output_dir", "manifest_path", "downloaded"},
			Examples: []string{"luma-cli image generate \"窗帘产品短视频封面背景\" --count 2 --aspect-ratio 9:16"},
			Skills:   []string{"luma-video-workflow"},
		},
		{
			ID:          "video.generate",
			Service:     "video",
			Command:     "generate",
			Description: "Generate a short video from a prompt and first-frame image through the cloud media API.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "prompt", Description: "Video generation prompt.", Required: true},
				{Name: "image", Description: "Local first-frame image path.", Required: true},
				{Name: "image-key", Description: "Cloud first-frame object key. Skips upload."},
				{Name: "duration", Description: "Video duration in seconds.", Default: "4"},
				{Name: "aspect-ratio", Description: "Output aspect ratio.", Default: "9:16"},
				{Name: "resolution", Description: "Output resolution.", Default: "720p"},
				{Name: "output", Description: "Output mp4 path.", Default: "generated_video.mp4"},
			},
			Outputs:  []string{"task_id", "output_path", "manifest_path", "downloaded"},
			Examples: []string{"luma-cli video generate \"镜头缓慢推进，窗帘随风摆动\" --image first_frame.png --duration 4"},
			Skills:   []string{"luma-video-workflow"},
		},
		{
			ID:          "subtitle.render",
			Service:     "subtitle",
			Description: "Generate styled subtitles and optionally burn them into a video.",
			Risk:        "write",
			Flags: []common.Flag{
				{Name: "video_or_text", Description: "Local video file path, or raw text with --text.", Required: true},
				{Name: "text", Description: "Treat positional input as raw text."},
				{Name: "output", Description: "Output video path.", Default: "step5_subtitle.mp4"},
				{Name: "segments-output", Description: "Output segment JSON path for PIP planning."},
				{Name: "project", Description: "Project name for organized outputs."},
				{Name: "max-chars", Description: "Maximum characters per subtitle segment.", Default: "15"},
			},
			Outputs:  []string{"output_path", "ass_path", "segments"},
			Examples: []string{"luma-cli subtitle input.mp4 --project demo"},
			Skills:   []string{"luma-subtitle", "luma-video-workflow", "luma-workflow-viral-remix"},
		},
	}
}
